[package]
name = "quasar"
version = "0.1.0"
authors = ["Anthony Nowell <anowell@gmail.com>"]

[dependencies]
mustache = "0.8.0"
rustc-serialize = "0.3.18"


[dependencies.webplatform]
git = "https://github.com/anowell/rust-webplatform.git"
