[package]
name = "maudapp"
version = "0.1.0"
authors = ["Anthony Nowell <anowell@gmail.com>"]

[dependencies]
maud = "0.14.0"
maud_macros = "0.14.0"

[dependencies.quasar]
path = "/home/anowell/proj/quasar"
default-features = false
